name: xo
description: mini web framework
version: 1.0.2
homepage: https://github.com/MiYogurt/xo
author: ChenMingMing <belovedyogurt@gmail.com>


publish_to: https://pub.dartlang.org/

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.0
  meta: ^1.1.7
  
dev_dependencies:
  build: ^1.1.1
  build_config: ^0.3.1
  build_runner: ^1.2.4
  build_web_compilers: ^1.1.0
